---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/Berlin"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "npm"
    directory: "/angular-example"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/Berlin"
    pull-request-branch-name:
      separator: "-"
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/react-example"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/Berlin"
    pull-request-branch-name:
      separator: "-"
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/react-tailwind-template"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/Berlin"
    pull-request-branch-name:
      separator: "-"
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/vue-example"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/Berlin"
    pull-request-branch-name:
      separator: "-"
    versioning-strategy: increase
