import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@db-ui/components/build/styles/db-ui-42-webpack.css";
import "./globals.css";
import {
  DBHeader,
  DBBrand,
  DBLink,
  DBButton,
  DBMainNavigation,
  DBNavigationItem,
} from "@db-ui/react-components";
import { Header } from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body data-density="regular">
        <Header />
        {children}
      </body>
    </html>
  );
}
